#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy

# Listen to web_1 and web_2 servers                                                                                                                                                                                     

echo "
frontend cypriancodes.tech
   bind 0:80
   default_backend webservers

backend webservers
   balance roundrobin
   server 333528-web-01 18.235.234.60:80 check
   server 333528-web-02 18.207.140.208:80 check
   " >> /etc/haproxy/haproxy.cfg

   # Restart HAproxy service
service haproxy restart
