#!/usr/bin/env bash
# Update Nginx configuration to run as the nginx user
sudo useradd -r -s /sbin/nologin nginx

sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Modify the default site configuration to make Nginx listen on port 8080
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default

sudo systemctl restart nginx
